# == == == == == === == == == == == #
#      Prison 3 Configuration       #
# Be sure to check your formatting! #
# == == == == == === == == == == == #

# The storage engine that Prison should use to store data.
# Ensure that only one is left uncommented out. Also, ensure
# that you specify your MongoDB or SQL login credentials if necessary.
storageType: "json"
#storageType: "mongo"
#storageType: "sql"

# Login credentials for MongoDB
mongo:
  host: localhost
  database: prison
  username: root
  password: root
  port: 3306

# Login credentials for SQL.
sql:
  host: localhost
  database: prison
  username: root
  password: root
  port: 3306
