name: Prison
main: me.faizaand.prison.spigot.SpigotPrison
version: "${version}"
description: Prison is an all-in-one plugin for the Minecraft prison game mode.
website: https://faizaand.me/prison
softdepend: [Essentials, Vault, LuckPerms, Multiverse-Core, Multiworld, MVdWPlaceholderAPI]

permissions:

  # ==================
  # Core permissions
  # ==================

  prison.modules:
    description: Access to the /prison modules command.

  prison.convert:
    description: Access to the /prison convert command.

  prison.alerts:
    description: Access to the /prison alerts command, and the ability to be notified for new alerts.

  prison.alerts.clear:
    description: Clear your alerts.

  prison.alerts.clear.all:
    description: Clear the alerts for the entire server.

  # Permission Kits
  prison.admin:
    description: Administrative access to Prison's functionality.
    default: op
    children:
      prison.modules: true
      prison.convert: true
      prison.alerts: true
      prison.alerts.clear: true
      prison.alerts.clear.all: true

  # ==================
  # Mines permissions
  # ==================

  mines.create:
    description: Access to the /mines create command.

  mines.set:
    description: Access to the /mines set command.

  mines.block:
    description: Access to the /mines block command.

  mines.delete:
    description: Access to the /mines delete command.

  mines.info:
    description: Access to the /mines info command.

  mines.wand:
    description: Access to the /mines wand command.

  mines.list:
    description: Access to the /mines list command.

  mines.reset:
    description: Access to the /mines reset command.

  mines.admin:
    description: Contains all the commands for managing mines.
    default: op
    children:
      mines.create: true
      mines.set: true
      mines.block: true
      mines.delete: true
      mines.info: true
      mines.wand: true
      mines.list: true
      mines.reset: true

  # ==================
  # Ranks permissions
  # ==================

  ranks.user:
    description: Allows users to see the ranks and rank up.
    default: true

  ranks.command:
    description: Access to the /ranks command command.

  ranks.ladder:
    description: Access to the /ranks ladder command.

  ranks.info:
    description: Access to the /ranks info command.

  ranks.list:
    description: Access to the /ranks list command.

  ranks.create:
    description: Access to the /ranks create command.

  ranks.delete:
    description: Access to the /ranks delete command.

  ranks.admin:
    description: Contains all the commands reserved for admins.
    default: op
    children:
      ranks.user: true
      ranks.command: true
      ranks.ladder: true
      ranks.info: true
      ranks.list: true
      ranks.create: true
      ranks.delete: true
