name: Prison
main: tech.mcprison.prison.spigot.SpigotPrison
version: "${version}"
description: Prison is an all-in-one plugin for the Minecraft prison game mode.
website: https://mc-prison.tech
softdepend: [Essentials, Vault, LuckPerms]

permissions:
  prison.alerts:
    description: Permission to view alerts.
    default: op
